# buildspec.yml

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt
      - python -m pytest tests/automated_tests/

      version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Build started on `date`"
      - pip install -r requirements.txt
      - python -m pytest tests/automated_tests/
      - echo "Build completed on `date`"
